name: Build & Deploy Go project to Raspberry Pi
on:
    push:
        branches:
            - master
jobs:
    build-push-deploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Install QEMU and Docker Buildx
              run: |
                  docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
                  docker buildx create --name mybuilder --use
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push Docker images
              run: |
                  docker buildx build --platform linux/arm/v7 -t mluksic/internet-speed-tracker --push .
            - name: Deploy with Docker Compose
              run: |
                  cd /home/pi/actions-runner/_work/internet-speed-tracker/internet-speed-tracker
                  docker-compose pull
                  docker-compose up -d
